# configs/gene_filter_analysis.yaml

gene_filter:
  # 원본 데이터(Excel)가 있는 폴더 경로
  # raw_data_dir: "data/processed" # 더 이상 사용하지 않음
  in_csv_file: "standardized.csv" # 입력 파일을 CSV로 변경

  # 분석 결과가 저장될 출력 폴더 경로
  output_dir: "gene_filter_analysis_report" # ROOT_DIR 기준 상대 경로

  # 분석 대상 유전자 목록 파일
  gene_list_file: "configs/genes_of_interest.txt" # 프로젝트 루트 기준 경로

  # 컬럼 이름 매핑
  column_map:
    gene: "gene"
    log2fc: "log2fc"
    padj: "padj"
